import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio: Alex G Friedman</title>
        <meta name="description" content="Generated by create react app lol"></meta>
        <link rel='icon' href="favicon.ico" />
      </Head>
      <main></main>
    </div>  
  )
}
