import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio: Alex G Friedman</title>
        <meta name="description" content="Generated by create react app lol"></meta>
        <link rel='icon' href="favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Alex Friedman codes</h1>
            <ul className='flex items-center'>
              <li> <BsFillMoonStarsFill className='cursor-pointer text-xl'/></li>
              <li> <a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
              <li> <a href='#/blog' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Blog</a></li>
            </ul>
          </nav>
          <div>
            <h2>Alex G Frieman</h2>
            <h3>Developer and Writer</h3>
            <p>Experienced in Ruby on Rails and JavaScript-based programming and a background in higher education. 
Solution oriented, creative approach to app design with a focus on delivering users an intuitive interactive experience.
            </p>
          </div>
          <div>
            <a href='https://github.com/friedmanalexg'><AiFillGithub /></a>
            <a href='https://www.linkedin.com/in/alex-friedman-codes/'><AiFillLinkedin /></a>
          </div>
        </section>
      </main>
    </div>  
  );
}
