import Head from 'next/head';
import Image from "next/image";

export default function Page() {
  return (
    <div>
      <Head>
        <title>Portfolio: Alex G Friedman</title>
        <meta name="description" content="Generated by create react app lol"></meta>
        <link rel='icon' href="favicon.ico" />
      </Head>
      <main className='px-6 mx-auto'>
        <h2>Hello World!</h2>
      </main>
    </div>
  );
}