//declare use client for nextjs default server components
'use client';
//importing
import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import Image from "next/image";

//blog page
export default function Page() {
  return (
    <div>
      <Head>
        <title>Portfolio: Alex G Friedman</title>
        <meta name="description" content="Generated by create react app lol"></meta>
        <link rel='icon' href="favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
        <nav className='dark:text-white py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white text-gray-800'>Alex Friedman codes</h1>
            <ul className='flex items-center'>
              <li> <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl dark:text-white text-gray-800'/></li>
              <li> <a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
              <li> <a href='/blog' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Blog</a></li>
            </ul>
          </nav>
        </section>

      </main>
    </div>
  );
}